core/deps/chdpsr/cdipsr.cpp
core/deps/chdpsr/cdipsr.h
core/deps/coreio/coreio.cpp
core/deps/coreio/coreio.h
core/imgread/cdi.cpp
core/imgread/common.h
core/imgread/gdi.cpp

- Fix coreio fsize
- Fix coreio fopen to seek to 0
- Fix coreio/http to smart-escape urls
-  For urls that include \ or % in the filenames, you have to pass them
escaped
- Update gdi parser to use (mostly) streamstream. That code is horrible
and should be rewritten
- coreio core is hacky and horrible at places as well
- Update imgreader to use coreio
- Update cdi parser + driver to use coreio

http support for cdi & gdi, updated based gdipsr

---

core/cfg/cfg.cpp
core/cfg/cfg.h
core/cfg/cl.cpp
core/hw/gdrom/gdromv3.cpp
core/nullDC.cpp
core/reios/reios.cpp
core/reios/reios_elf.cpp
core/reios/reios_elf.h
core/types.h
core/windows/win86_driver.cpp
shell/reicast.vcxproj
shell/reicast.vcxproj.filters

This implements elf booting via reios, using the existing elf parser (which is/was needed as part of reprof)
As a bonus, .elf, .cdi and .chd files are now automatically detected on the command line. 
`./reicast.elf game.elf game.cdi` will boot without asking for cd, trying to mount `game.cdi`
`./reicast game.chd` and `./reicast game.cdi`  will try to boot that image.
These are just shorthands for -config reios:ElfFile=... and -config config:image=....

reios: Add support for elf booting

---

shell/android/res/values-de/strings.xml

- This fixes typos and other mistakes in the german translations - mostly the so-called "Deppenleerzeichen" (wrongfully inserted spaces in composed words). Refer to http://de.wikipedia.org/wiki/Leerzeichen_in_Komposita for details.
- This also adds german translations for all strings in `shell/android/res/values/strings.xml`.
- The ordering of the strings now corresponds to `shell/android/res/values/strings.xml`.

Fix german translations

---

.travis.yml
core/core.mk
core/linux/common.cpp
core/linux/nixprof.cpp
core/rec-ARM/ngen_arm.S
shell/android/jni/Android.mk
shell/android/jni/Application.mk
shell/android/project.properties
shell/android/res/values-ko/strings.xml

Today I found out that android by default exports all symbols, and uses dynamic linking on them. This applies even for "internal" symbols, as everything is exported by default. Some other opts were enabled too, and minor changes on nixprof/common/travix for ndk r10d.
- Makes all symbols hidden by default (pro tip: `nm -D <so file>`)
- Disables all debug info. Debug info is *not* always zero cost on gcc.
- Enable per function GC
- ndk r10d uses same register names as desktop linux (yay!)
Would be great if someone tested the speed of these changes and reported back. Use [this CI build apk](http://reicast-builds.s3.amazonaws.com/builds/heads/features/use-ndk-r10d-7abd154/reicast-android-debug-7abd154.apk).

Update for ndk-10d, improved build options

---

core/rec-ARM/arm_dyna.cpp

Using default arguments is only allowed in function declarations, not
in typedefs. This fixes the invalid code that caused compilation errors
on systems using GNU g++ 4.9.2, i.e.:
> ../../core/rec-ARM/arm_dyna.cpp: At global scope:
> ../../core/rec-ARM/arm_dyna.cpp:186:79: error: default arguments are only permitted for function parameters
>  typedef void FPBinOP        (eFSReg Sd, eFSReg Sn, eFSReg Sm, ConditionCode CC=CC_AL);
>                                                                                ^
> ../../core/rec-ARM/arm_dyna.cpp:187:79: error: default arguments are only permitted for function parameters
>  typedef void FPUnOP         (eFSReg Sd, eFSReg Sm,            ConditionCode CC=CC_AL);
>                                                                                ^
> …

Remove arm_dyna typedef default args

---

core/hw/pvr/pvr_mem.cpp
core/hw/pvr/ta_vtx.cpp

This should fix some NAOMI issues, which don't quite apply (yet). Thanks to @inolen on irc for the long conversation about the issue, which made me realize where the old handling was wrong :dancers:

pvr/vram: Bank bit seems to be fixed on 4M, even on 16M hardware

---

core/hw/sh4/interpr/sh4_opcodes.cpp

This partly resolves #660 (needs to applied to linux-64 branch, too).

sh4_opcodes: Fix printf arguments

---

core/hw/sh4/interpr/sh4_opcodes.cpp

This resolves #660 (basically the changes from commit fb50c75 applied
to the 'skmp/linux-64' branch. As an alternative, puts() could be used
instead of prinf().

sh4_opcodes: Fix printf arguments (skmp/linux-x64 branch)

---

core/linux/common.cpp

Not sure why it's dying on start yet for me, but it was doubly-mysterious when it exited instead of dumping some useful info.

linux: print memory map to stderr when fixed path not available

---

core/hw/mem/_vmem.cpp

Wasn't actually putting the returncode of shm_open to fd
This code could do with a cleanup though -  as it doesn't need to fallback anymore is the fallback code needed ? fd doesn't need to be initialised either. Not sure if this branch is still in development or not really, so I'll leave that to you. Cheers.

Fix shm_open on the rpi

---

core/oslib/audiostream.cpp

There is an initialization warning which is enough to warn users

Audiostream: Don't log on every push if audio is disabled

---

core/hw/maple/maple_devs.cpp

This makes it possible to work on a read-only fs

maple: Gracefully fail if vmu cannot be written

---

core/hw/sh4/dyna/shil_canonical.h

Using external function pointers is broken after the rec-cpp structural changes,
and relatively low priority so disabled for now.
Fixes builds on arm, non-android (see #720)

shil: Disable external assembly implementations

---

shell/linux/Makefile

This adds support for the ODROID-C1/C1+/X/X2/U2/U3/XU/XU3/XU4 single board computers by Hardkernel.
Makes #708 obsolete.
This is a follow-up PR to #705. Unlike #605, this PR just adds some Makefile definitions (no code changes). I compiled and tested on an ODROID-C1 and everything seems to work as expected. ~~**EDIT:** Strange, I rebased and currently get some strange errors:~~ **FIXED**
```
In file included from ../../core/hw/sh4/dyna/shil.cpp:1012:0:
../../core/hw/sh4/dyna/shil_canonical.h: In static member function 'static void shil_opcl_fipr::compile(shil_opcode*)':
../../core/hw/sh4/dyna/shil_canonical.h:14:19: error: 'fipr_asm' is not a class or namespace
#define fipr_impl fipr_asm
^
../../core/hw/sh4/dyna/shil_canonical.h:56:87: note: in definition of macro 'shil_compile'
#define …
```

Add ODROID-C1/C1+/X/X2/U2/U3/XU/XU3/XU4 support

---

shell/linux/Makefile

This is a modified version of PR #757 (which breaks ARM).
I check if it's an ARM build (NOT_ARM not defined) and then set `$(AS)` to `gcc` and append `$(CFLAGS)` to `$(ASFLAGS)`.
@skmp Is this correct? Does every ARM build use `gcc` as `$(AS)`?
If so, It *should* work fine. ~~I'm currently testing on my ODROID.~~ **EDIT:** Works fine on my ODROID-C1.

Makefile: Fix Linux_x86

---

core/hw/sh4/sh4_mem.cpp
core/reios/reios.cpp

- Setups state, copies binary
- Binary locks up w/ a reboot loop
Naomi roms have a 512-byte header, executable length seems to be
at 368 or 3C0. The rom is copied from [0, len) to 0x0c020000.The
bios then hands over control at 0x0c021000

reios/naomi: First baby steps to support booting naomi roms

---

wercker.yml

This will build reicast for Linux x64 on Ubuntu. ARM/x86 support is still missing though.

[Wercker] Add preliminary wercker.yml for Linux_x64 building

---

appveyor.yml
shell/reicast.sln

Getting everything working for appveyor, building all 4 configurations

msvc: Update sln files to use "x86" instead of "win32" for appveyor

---

core/nullDC.cpp

According to the search function, `OMAP4` isn't set anywhere, so this shouldn't be a problem.
The other stuff also doesn't belong there IMHO. Guess this was testing code that hasn't been removed yet.

nulldc: Remove some hardcoded values

---

core/cfg/cl.cpp

(Updated) summary:
* `.gdi` files support as CLI arguments;
* case insensitive file extension matching (only at the end of the file name).

Handle .gdi files on the CLI (and other enhancements)

---

appveyor.yml

- Add S3 credentials, bucket reicast-builds-windows
- Don't split platform with - (win_x86 and win_x64, makes for easier regex)
- Naming consistent with current android builds naming

Appveyor: Deploy to S3

---

shell/linux/Makefile

It can be useful in places like launchpad farm.

Add a generic 32-bit ARM rule.

---

core/hw/sh4/interpr/sh4_interpreter.cpp
core/hw/sh4/interpr/sh4_opcodes.cpp
core/hw/sh4/modules/mmu.cpp
core/hw/sh4/modules/mmu.h
core/hw/sh4/modules/mmu_impl.h
core/hw/sh4/sh4_interrupts.cpp
core/hw/sh4/sh4_mem.h
shell/reicast.vcxproj
shell/reicast.vcxproj.filters

Reicast doesn't support exceptions yet, so this isn't of much use now,
and is intended mostly as documentation. nullDC used some call stack
hooking magic to handle exceptions, which was never generic and clean
enough to be worth the effort to port to Reicast.

sh4/mmu: Import the old mmu implementation from nullDC.

---

core/cfg/cfg.cpp
core/hw/maple/maple_devs.cpp
core/hw/mem/_vmem.cpp
core/hw/sh4/dyna/blockmanager.cpp
core/hw/sh4/dyna/driver.cpp
core/hw/sh4/sh4_mem.cpp
core/linux-dist/evdev.cpp
core/linux-dist/main.cpp
core/linux/nixprof/nixprof.cpp
core/nacl/nacl.cpp
core/nullDC.cpp
core/rend/gles/gles.cpp
core/sdl/main.cpp
core/stdclass.cpp
core/stdclass.h
core/webui/server.cpp
core/windows/winmain.cpp
shell/android/jni/src/Android.cpp
shell/apple/emulator-ios/emulator/ios_main.mm
shell/apple/emulator-osx/emulator-osx/osx-main.mm

This one has grown a bit bigger than I expected. Anyhow, I here's a description what this PR does:
It replaces the `GetPath` function with two dedicated functions:
```C++
get_config_path(filename);
get_data_path(filename);
```
The first one gets a path for a config file (we currently only have `emu.cfg`). The second one gets a path for a data file (e.g. `buttons.png`, the VMU saves or the BIOS/Flashrom).
I did this separation, because on some platforms, the stuff is actually saved in different places - on Linux, this is `$HOME/.config/reicast` for config stuff and `$HOME/.local/share/reicast` for data files (see [XDG Basedir Spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)).
I also added support for distinguishing writable and read-only files. Both functions …

Introduce separate config/data dirs (user & system wide)

---

core/deps/libelf/elf.cpp
core/deps/libelf/elf.h
core/deps/libelf/elf64.h
core/hw/pvr/Renderer_if.cpp
core/linux-dist/main.cpp
core/linux-dist/x11.cpp
core/linux/nixprof/nixprof.cpp
core/profiler/profiler.h

* Make it available on X11
* Make it work with ELF64
* Use .symtab if available instead of .dynsym
* Only process STT_FUNC symbols
* Use section types and links insteaf of section names to find symbol and string table sections
Some modifications to deps/libelf. Is this code maintained at https://github.com/seL4/libelf? Needs to be upstreamed.
Might be a good idea to use perf or directly perf_event_open (faster, less intrusive, lots of features). For the former, a /tmp/perf-$PID.map can be used to bind SH4 blocks to host addresses.

Nixprof: some enchancements

---

shell/linux/tools/reicast-joyconfig.py

This should fix the bug described in https://github.com/reicast/reicast-emulator/issues/427#issuecomment-141253833.

Linux/reicast-joyconfig: Fix error handling for Python < 3.0

---

core/oslib/audiobackend_coreaudio.cpp
core/oslib/audiobackend_coreaudio.h
core/oslib/audiostream.cpp
shell/apple/emulator-ios/reicast-ios.xcodeproj/project.pbxproj
shell/apple/emulator-osx/emulator-osx/EmuGLView.swift
shell/apple/emulator-osx/reicast-osx.xcodeproj/project.pbxproj

This needs to be lock correctly and buffer correctly before making it to master. But it's a place to start!
Sound does work on OS X, on iOS I get silence (but no crashes). iOS uses 1024 frame blocks and that could be one of the issues there

apple: Add primitive core audio support

---

core/hw/pvr/Renderer_if.cpp
core/nullDC.cpp
core/types.h

The simplest of simplest ways I could reduce testing that can scale. The logfiles can be architecture dependent, and there's no input logging yet.
-
This allows for some very primitive auto-automated testing, by comparing known good frames.
As this happens on the TA level, it doesn't actually require rendering (and thus it's server friendly)
Two new config entries under the new [testing] namespace control behavior
- ta.HashLogFile, file where data should be logged, empty if not logging
- ta.HashCheckFile, past log to check against, empty if not checking
The emu will crash via verify if the logs don't match, and exit(1) if they do

rend/if: Logging/verification of MD5(ta command list data)

---

core/linux-dist/main.cpp

I tried running reicast and it immediately died with:
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_S_construct null not valid
Aborted
I was missing the environment variable XDG_CONFIG_DIRS
Turns out find_system_config_dirs() checked for the existence of
XDG_DATA_DIRS but then tried to use XDG_CONFIG_DIRS (non-existent in my
case).
fixes #847

Fix the check for the enviroment variable

---

core/khronos/GL3/gl3w.c
core/rend/gles/gles.cpp
core/sdl/sdl.cpp
core/sdl/sdl.h
shell/linux/Makefile

~~Unfortunately, I needed to move to SDL2 to make this work. I'm not really happy with introducing yet another code path, so we should decide if we want to keep SDL1.2 support (without OpenGL3) or if we wan't to move to SDL2.~~
**EDIT:** What this PR does:
- Migrate from SDL1.2 to SDL2 and drop SDL1.2 support
- We can now initialize the OpenGL 3.1 context in a platform-independent way via SDL2 (SDL1.2 did not support OpenGL 3.1)
- OpenGL ES is also initialized via SDL2 instead of using custom EGL code (it's still there for Android though, but maybe we can also use SDL2 on Android?).
As a Bonus, I can now run reicast with OpenGL ES on my Linux desktop (the egl code always failed, but via SDL2 it works fine).

Move to SDL2 for OpenGL 3.1 and GLES support

---

core/linux-dist/evdev.cpp

Since EvdevControllerMapping does not have a default constructor,
we can't use the operator[];
data_type& operator[](const key_type& k) - Returns a reference to
the object that is associated with a particular key. If the map
does not already contain such an object, operator[] inserts the
default object data_type().
Instead, we use the std::map.find() function.

linux-dist/evdev: Use std::Map.find() instead of operator[]

---

core/oslib/audiobackend_alsa.cpp

Really minimal change to fix alsa initialization in some environments:
This variable is passed into alsa as a pointer. Alsa will write to it but also read (!) from it. So the read will give undesired behavior because variable was not initialized. Depending on current alsa-config/hardware it leads to an error "Invalid argument" when submitting the parameters by invoking "snd_pcm_hw_params" a few lines later.
Initializing the variable to -1 fixes it and means "set to exact value or less" (http://alsa.opensrc.org/HowTo_Asynchronous_Playback)

alsa-backend: initialize variable "sub unit dir"

---

shell/linux/Makefile

On older kernels, the Odroid-XU4 would be identified as "ODROID-XU3". On newer kernels, such as the latest Ubuntu kernel for ODroid, the XU4 is now being identifed as "ODROID-XU4" which would cause the hardware detection to fail and have it build a generic ARM build instead of our desired "platform = odroidxu3".

Fix hardware detection for Odroid-XU4 against newer kernels

---

shell/linux/Makefile

First time pull request so my apologies if I've failed a protocol.
---
The Vero4k is a "Kodi box" from OSMC.
The OS is built on Debian.
64bit.
Amlogic S905x SOC ->  ARM Cortex-A53  ->  armv8-a with Mali 450.
Builds straight from `make` with these changes and runs very well indeed.
Requires `git revert 6ae93b3` from ***master*** though, to avoid segfault on startup (#1032).

Added detection for Vero4K

---

core/emitter/x86_emitter.h

This appears to be a necessary duplicate for other platforms.

Restore secondary x86_ptr_imm for non-Windows

---

core/hw/pvr/ta_ctx.h

As per Issue #1032 there are seg faults with the changes from PR #1023 (ta: use 256-bit struct).
I confess I don't understand the purpose of the changes, optimisations no doubt, but reverting them still allows building and thankfully does not appear to have broken any subsequent commits.
If there are no objections this commit adds flags to the Makefile to keep the original code for these 2 platforms, so they can be built for Retropie etc.

Circumvent PR #1023 on RPI and Vero4K

---

core/hw/pvr/ta_ctx.h

Looks I somehow reverted half of the useful changes on the previous merge, duh. I need to find some nice visual diff tool for linux >.>
@hissingshark this should be alright now

tactx: Actually use aligned alloc functions

---

issue_template.md

This creates a "form" that will automatically populate when submitting new issues.
There are various options for how this is handled, including per-branch templates
https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/

Add a not-so simple template for issues

---

core/linux-dist/evdev.cpp
core/stdclass.h

Check if a configuration file named exactly like the device exists in the /mappings/ directory.
If it does, use this instead of the generic one.
Exposes ``file_exists()`` from stdclass.

evdev: Allow for custom <device>.cfg files in the /mappings/ directory.

---

core/types.h

As confirmed by MettalliC, the correct value is 32KB.

(Naomi) Fix for "The Rumble Fish 2"

---

shell/linux/tools/reicast-joyconfig.py

While trying to reproduce #1187 I recognized that reicast-joyconf could get some love.
I added information about the filename as which the configuration should be saved (see #1182) and another suggestion how evdev for python could be installed (on Debian/*buntu).

reicast-joyconf: cosmetic changes

---

core/linux-dist/evdev.cpp

On Linux the window stays black without any error message when a joystick/controller is connected and reicast was build with GCC8. This is probably due to changes made in GCC8. https://gcc.gnu.org/gcc-8/porting_to.html#Wreturn-type

Fix controller support for Linux when building with GCC8

---

core/linux-dist/joystick.cpp
core/linux/common.cpp
core/linux/context.cpp
core/oslib/audiobackend_oss.cpp
shell/linux/Makefile
wercker.yml

Probably not the most beautiful code changes but it works :)
- piggybacking on `HOST_OS==OS_LINUX` instead of introducing `OS_FREEBSD`, they're similar enough, so I'm keeping the changes small
- what's with `sys/unistd.h` and other standard headers under `sys/`?! in `audiobackend_oss.cpp`
- `true` is `/usr/bin/true` here — but just `true` is a shell builtin normally, why write `/bin/true`?

Build on FreeBSD

---

core/rend/gles/gles.cpp

Currently a compile time option (!GLES). Fixes many depth issues (Dynamite Cop, Cannon Spike, etc.)

GL3: Use log2 depth scaling in fragment shader

---

core/hw/aica/sgc_if.cpp

Fixes Bomberman Online FMV intro freeze, Jet Grind Radio and Psyvariar 2 intro music fade out and probably more.

Update AEG params when FNS or OCT registers are updated

---

shell/android-studio/reicast/src/main/java/com/reicast/emulator/GL2JNINative.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/GL2JNIView.java

This is not yet avoidable, but can at least be explained.

Android: restore hard exiting thread (w/ notes)

---

shell/android-studio/reicast/src/main/java/com/reicast/emulator/Emulator.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/OptionsFragment.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/JNIdc.java
shell/android-studio/reicast/src/main/jni/src/Android.cpp
shell/android-studio/reicast/src/main/res/layout-v14/configure_fragment.xml
shell/android-studio/reicast/src/main/res/layout/configure_fragment.xml
shell/android-studio/reicast/src/main/res/values/strings.xml

It is a boot disk, which would be the "default" disk. Labeling it default is misleading, though. It will also prevent confusion to have examples of common boot disks.

Android: Fix the misleading "default disk" setting

---

core/linux-dist/evdev.cpp
core/linux-dist/evdev.h
core/linux-dist/main.cpp

If a device is configured more than once that can be intentional, however assigning the same button for multiple players may not.
So print a warning in that case.
Follow up of #1273.

evdev: Check for duplicate key assignment

---

shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/OptionsFragment.java
shell/android-studio/reicast/src/main/res/layout-v14/configure_fragment.xml
shell/android-studio/reicast/src/main/res/layout/configure_fragment.xml

This option saves a path for an unimplemented feature. Rather than continue to field questions about how to use it because it is not connected to anything, it is better to disable it for now.

Android: Disable the boot disk option until valid

---

core/linux-dist/x11.cpp

Value -1 for example doesn't disable X11 keyboard input, only 0 does (non zero = enabled).
Changed that behavior to match other settings (where -1 means disabled, ``joystick_device_id`` f.e.) so that every value above zero means enabled and zero or less means disabled.
Also print an information if the X11 keyboard is disabled (like with legacy joystick support).
I noticed this investigating #1273.

X11: Values <= 0 disable keyboard

---

core/linux-dist/evdev.cpp

There is no need to check unassigned buttons (dpad2, D, Z f. e.) and this caused false positives.
Also removes the trailing white-spaces.
Follow up of #1277.

evdev/dupcheck: Don't check unassigned buttons

---

shell/linux/man/reicast.1

Reworked parts of the man file and added the information about the added functionality of #1182 (.cfg files named after the input device).
Fixes #1083.

man: add information about the named evdev config files

---

core/linux-dist/x11.cpp

Without those changes, it's not possible to compile reicast with GLES support and X11.
The resulting binary is working fine.

Fixes compiling with GLES and X11

---

core/linux-dist/evdev.cpp

Currently one does not necessary notice if a button/axis is unconfigured, so print a warning for each unassigned button.
Possible output:
````
btn_a = KEY_LEFTSHIFT (42)
btn_b = KEY_RIGHTCTRL (97)
WARNING: dreamcast/btn_c not configured!
WARNING: dreamcast/btn_d not configured!
btn_x = KEY_LEFTCTRL (29)
btn_y = KEY_LEFTALT (56)
WARNING: dreamcast/btn_z not configured!
btn_start = KEY_1 (2)
btn_escape = KEY_J (36)
btn_dpad1_left = KEY_LEFT (105)
btn_dpad1_right = KEY_RIGHT (106)
btn_dpad1_up = KEY_UP (103)
btn_dpad1_down = KEY_DOWN (108)
WARNING: dreamcast/btn_dpad2_left not configured!
WARNING: dreamcast/btn_dpad2_right not configured!
WARNING: dreamcast/btn_dpad2_up not configured!
WARNING: dreamcast/btn_dpad2_down not configured!
btn_trigger_left = KEY_SPACE (57)
WARNING: …
```

evdev: Print a warning if a key is not configured

---

shell/android-studio/reicast/src/main/java/com/reicast/emulator/GL2JNIActivity.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/GL2JNINative.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/Config.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/InputFragment.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/OptionsFragment.java
shell/android-studio/reicast/src/main/jni/src/Android.cpp
shell/android-studio/reicast/src/main/res/layout-v14/configure_fragment.xml
shell/android-studio/reicast/src/main/res/layout/configure_fragment.xml
shell/android-studio/reicast/src/main/res/values/strings.xml

This will maintain restricting access to direct creation, while still allowing the workaround of setting the microphone to an obligatory port.

Android: Pass microphone setup through controller

---

core/linux-dist/main.cpp

If USE_EVDEV is not defined then it will complain about MapleDeviceType not being defined (see line 108 in core/linux-dist/main.cpp)...
The resulting binary still works btw but i've only tested it against Void linux Musl x86_64 so pls test thx

Fixes compiling if evdev is disabled

---

core/emitter/x86_emitter.h
core/linux/common.cpp

This allows checking against the whole library of definitions specifically for Mac, including the wondrous `TARGET_OS_MAC` that checks for anything Apple-based.

Mac: Reference "official" preprocessor directives

---

core/linux-dist/evdev.cpp
core/linux-dist/evdev.h
core/linux-dist/main.cpp

That way we don't need to reserve memory and the output (on the command line) is correct.
After another round I got it right...

evdev: Mapping name as string

---

core/linux-dist/evdev.cpp

Many Linux distributions provide livevdev.so.2 only so check that first.
See https://packages.debian.org/sid/amd64/libevdev2/filelist for Debian. You would need to create a symlink yourself or install ``libevdev-dev`` (see https://packages.debian.org/sid/amd64/libevdev-dev/filelist) which no normal user should have installed as it's a developer package.
Fixes #1336

evdev: Search for libevdev.so.2 first

---

core/imgread/common.cpp

If no image was loaded (or using ioctl) the CDI warning was always printed.

CDI: Only warn if CDI image was really loaded

---

core/linux-dist/evdev.cpp

If the controller was not correctly initialized, the fd and/or the mapping might not be set, which could then result in access violations or other errors.
This fixes #1380.

evdev: If there was an error initializing a controller, don't proceed

---

appveyor.yml

We already set os to VisualStudio 2015, but the toolset was still set to v120 (VS 2013).

AppVeyor: Enable v140 toolset

---

core/hw/pvr/ta_ctx.h
core/hw/pvr/ta_vtx.cpp

Increase vertices, indices and translucent polygons max count.
Fixes crashes in D2 and Triggerheart Exelica:
https://github.com/reicast/gamedb/issues/123
https://github.com/reicast/gamedb/issues/63

Detect TA overruns and cancel the rendering. Increase TA data size

---

core/hw/holly/sb_mem.cpp

Do not crash on unaligned VRAM read access. Just return 0.

---

core/hw/pvr/ta.cpp

Fixes crashes in Looney Tunes Space Race, Test Drive Le Mans and others.

Some games send TA data without calling ListInit first. Don't crash in that case

---

core/hw/sh4/dyna/shil_canonical.h
core/hw/sh4/interpr/sh4_fpu.cpp
core/rec-x86/rec_x86_il.cpp

Fix for interpreter, common dynarec and x86 rec.
Fixes wrong car color in Tokyo Xtreme Racer car selection screen.

sh4: Fix FTRC (ipr, canonical, x86) by using correct positive cutoff value

---

core/hw/aica/aica_if.cpp
core/nullDC.cpp
core/types.h

Schedule the interrupt signaling the end of an Aica DMA transfer instead of raising it immediately.
Fixes Street Fighter Alpha 3 and Bomberman Online

Schedule the interrupt signaling the end of an Aica DMA transfer

---

core/sdl/sdl.cpp

This unbreaks input support with SDL (for the moment).
While reworking the input (#1288, #1308) I accidentally broke SDL input support because no controller is created in this case if **only** SDL is available (else the evdev configuration would create the necessary controllers and therefore the events are triggered).

SDL: Create the first controller with two VMUs

---

README.md

Fixes the URL to the snap/README.md in our main README.md

README/Snap: Fix URL to snap/README.md

---

core/imgread/cdi.cpp

Adopt https://github.com/reicast/reicast-emulator/commit/bffccac5a65860a84e8eb59cc689795f515fee9a from @flyinghead

CDI: coreio file handle leak in cdi image reader

---

shell/android-studio/reicast/src/main/java/com/reicast/emulator/Emulator.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/OptionsFragment.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/JNIdc.java
shell/android-studio/reicast/src/main/jni/src/Android.cpp
shell/android-studio/reicast/src/main/res/layout-v14/configure_fragment.xml
shell/android-studio/reicast/src/main/res/layout/configure_fragment.xml
shell/android-studio/reicast/src/main/res/values/strings.xml

Clipping is disabled by default on Android platform, so I decided to add a switch in settings menu to be able to turn on this option (disabled by default). Clipping implementation by @flyinghead is already present in the master branch.
When clipping is disabled split screen / multiplayer mode is rather non-playable (THPS2):
When we enable the clipping (THPS2):

Clipping switch in settings added - Android (multiplayer/split screen fixed)

---

core/linux-dist/main.cpp
core/sdl/sdl.cpp
core/sdl/sdl.h

This adds support for rumble to the SDL backend.
It does not however attach a purupuru/rumble pack.
This is one part to make the SDL input backend on par with the evdev backend (#1371, #340).
After that work is done, I think we can work on a more unified input backend implementation like the audiobackend (see #843, #823).

SDL: rumble support

---

core/oslib/audiobackend_alsa.cpp

Trying to load the device from the ``~/.config/reicast/emu.cfg`` section ``alsa`` and if not set (should be the default for everyone currently) use the existing procedure to try to determine the device (``default`` > ``plughw:0,0,0`` > ``plughw:0,0``).
If the init was successfull write the result back to the configuration file to make the next start a bit faster.
If the device is set then just try to use this as the ALSA device.
Also removes two unused variables while we're at it.
Closes #1483

ALSA: configurable output device

---

shell/android-studio/reicast/src/main/res/xml/provider_paths.xml

This PR fixes game booting issue on Android: https://github.com/reicast/reicast-emulator/issues/1488 by partially reverting commit: 4a3bec95f8ae9aadda10c6e5ae0303b3754e0a14
Please review and merge.
@AbandonedCart FYI

Fix: Instead of booting a game, reicast opens bios menu

---

shell/android-studio/reicast/src/main/java/com/reicast/emulator/GL2JNIActivity.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/EditVJoyActivity.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/GLCFactory.java

This fixes #1451 by cherry-picking https://github.com/reicast/reicast-emulator/commit/9c4085ee1ee42f85fc31aaf0bc2e01e3e16024d8 from @flyinghead and correcting the stencil buffer size in the Java code.

Android: fix full-screen shadow on some platforms

---

appveyor.yml

We only built Debug versions using appveyor and uploaded them as "-slow". 
Now we're only building Release versions and the "-slow" part of the filename is replaced with the name of the configuration used ("-Release").

CI/Windows: Build Release only

---

core/imgread/gdi.cpp

This cherry-picks https://github.com/reicast/reicast-emulator/commit/34f46fb4822ea34bc1d1fc23b58d3604c24b39c3 from @flyinghead

gdi: set correct CTRL value in TOC

---

core/nullDC.cpp
core/rend/gl4/gl4.h
core/rend/gl4/gldraw.cpp
core/rend/gl4/gles.cpp
core/rend/gles/glcache.h
core/rend/gles/gldraw.cpp
core/rend/gles/gles.cpp
core/rend/gles/gles.h
core/rend/gles/imgui_impl_opengl3.cpp
core/rend/gui.cpp
core/types.h

New option to disable fog effects
Fix GL state cache that was always disabled
put all shaders in a map and set uniforms once each frame
Use the GL cache in imgui, avoid saving/restoring state

GL renderer optimizations for low-end devices

---

core/hw/aica/aica.cpp
core/hw/aica/aica_if.cpp
core/hw/aica/aica_if.h
core/hw/maple/maple_cfg.cpp
core/hw/maple/maple_devs.cpp
core/hw/sh4/interpr/sh4_interpreter.cpp
core/nullDC.cpp
core/rend/gl4/abuffer.cpp
core/rend/gl4/gl4.h
core/rend/gl4/gldraw.cpp
core/rend/gl4/gles.cpp
core/rend/gles/glcache.h
core/rend/gles/gldraw.cpp
core/rend/gles/gles.cpp
core/rend/gles/gles.h
core/rend/gles/imgui_impl_opengl3.cpp
core/rend/gui.cpp
core/types.h
core/windows/winmain.cpp
shell/android-studio/reicast/src/dreamcast/AndroidManifest.xml
shell/android-studio/reicast/src/main/AndroidManifest.xml
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/JNIdc.java
shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/NativeGLView.java
shell/android-studio/reicast/src/main/jni/src/Android.cpp
shell/android-studio/reicast/src/naomi/AndroidManifest.xml

- New option to display VMUs in game 
- Android: run renderer in a separate native thread 
- Android: add activity alias for intents backward-compatibility 
- AW: fix coin input. Subclass sega controller instead of #def 
- AW: setup maple controls depending on game 
- GL: Don't use screen stretching parameter for RTT 
- GL: 90deg screen rotation option. Fix scissor/clip wrt scale/stretch

Float VMU option. Android renderer native thread. 90° screen rotation option. AW fixes. 

---

core/nullDC.cpp
core/oslib/audiobackend_alsa.cpp
core/oslib/audiobackend_coreaudio.cpp
core/oslib/audiobackend_directsound.cpp
core/oslib/audiobackend_libao.cpp
core/oslib/audiobackend_omx.cpp
core/oslib/audiobackend_oss.cpp
core/oslib/audiobackend_pulseaudio.cpp
core/oslib/audiostream.h
core/rend/gui.cpp
core/types.h
shell/android-studio/reicast/src/main/jni/src/Android.cpp

The settings can be defined by each audio backend (currently only alsa is implemented) and of different types (integer with min and max value, checkbox and a list with a callback).
I think this is now ready for the moment as any further work can be done by subsequent prs.

AUDIO: Allow backend specific settings

---

shell/android-studio/reicast/src/dreamcast/AndroidManifest.xml
shell/android-studio/reicast/src/main/AndroidManifest.xml
shell/android-studio/reicast/src/naomi/AndroidManifest.xml

The latest reicast builds displayed a redundant second launcher icon in the app drawer, due to a change in #1548.  This fixes the issue by removing the duplicate intent filters causing the redundant icon to display.

Android: remove duplicate intent filters

---

core/rend/gl4/gles.cpp
core/rend/gles/gles.cpp

Fixes missing bottom half-screen in Mr Driller (PAL, 60 Hz #1582 ), Kaen Seibo,
Mahjong Taikai II Special, Pon'n'Music 1 and 2 when in TV Composite and
RGB.
Fixes stretched screen in Cho - Hatsumei Boy Kanipan.

fix scissor test and vertical scaling when using the Y scaler

---

core/oslib/audiobackend_sdl2.cpp
shell/linux/Makefile

The backend supports 44.1KHz and 48KHz (with resamping). The resampler
is not great, has some noise but no idea where it comes from.
This enables the switch port, since using SDL2 is the quickest way
to get audio working.
TODO: Add support in the cmake, once cmake is fixed at master/HEAD.

Add SDL2 audio backend.

---

core/hw/pvr/Renderer_if.cpp
core/linux-dist/x11.cpp

Fallback to GL 3.1 when GL 4.3 isn't available was broken. Issue #1590 
Fallback to GL 3.0 instead of 3.1.
Fix crash when switching renderer (per-pixel, per-triangle)

x11: fix fallback to gl 3.0. fix crash when switching renderer.

---

core/rec-x86/rec_x86_driver.cpp

I guess that's why Win32 fails too

Hack-fix the x86 JIT so that it builds.

---

core/imgread/ioctl.cpp
core/rend/d3d11/d3d11.cpp
core/rend/gles/gles.cpp
core/stdclass.h
core/windows/winmain.cpp
core/windows/xinput_gamepad.h
shell/linux/Makefile

Doenst like the paths, big surprise. I tipically build it like:
make platform=win32 CXX=x86_64-w64-mingw32-g++ \
WINDRES=x86_64-w64-mingw32-windres \
CC=x86_64-w64-mingw32-gcc

Fix small issues for mingw builds on Linux

---

core/build.h
core/hw/aica/dsp_arm64.cpp
core/hw/arm7/arm64.cpp
core/hw/mem/_vmem.cpp
core/hw/mem/_vmem.h
core/hw/sh4/dyna/blockmanager.cpp
core/hw/sh4/dyna/driver.cpp
core/hw/sh4/dyna/ngen.h
core/linux/common.cpp
core/linux/posix_vmem.cpp
core/rec-ARM64/rec_arm64.cpp
core/rec-x64/rec_x64.cpp
core/windows/win_vmem.cpp

There's still stuff related to mprotect/mmap in places like Naomi and ARM-AREC, but I will ignore them for now.
Implemented the NO_RWX in the vmem and added support in the driver. Also added support for x64 and ARM64 recs. This is not meant to be used by general builds/releases but only for platforms which require it (Switch and perhaps UWP).

vmem API consolidation and implementation of NO_RWX

---

core/hw/sh4/dyna/blockmanager.cpp
core/hw/sh4/dyna/blockmanager.h
core/linux/common.cpp
core/rec-ARM64/rec_arm64.cpp
core/rec-x64/rec_x64.cpp
core/windows/win_vmem.cpp
core/windows/winmain.cpp

These includes a small rewrite of block manager blklist, to make it
more readable and perhaps even faster.
Tested on Win64(wine) and Linux32/64 (also tested it doesn't break
android arm64 since it changes some stuff there too).

Implement fast memory ops on x64

---

wercker.yml

Upgrade mutexes to cMutex to avoid issues on Windows
Seems that we cannot include stdclass.h from a header without
things going bad, due to some cyclic dependency in preprocessed
stuff?

Add more targets to Wercker, including Windows

---

core/build.h

| Platform | Branch | Hash | CIDL |
|---|---|---|---|
| S905x Mali 450 | Master | a6b773a | self build |
**_Description of the Issue_**
Previously successful builds.  Now fails with this commit.
**_Build output_**
```
obj-dreamcast-vero4k-neon/rend/gles/gldraw.build_obj: In function `render_output_framebuffer()':
/home/osmc/reicast-emulator/shell/linux/../../core/rend/gles/gldraw.cpp:1182: undefined reference to `glBlitFramebuffer'
collect2: error: ld returned 1 exit status
```
**_Debugging Steps Tested_**
* Bisected to commit `a6b773a`
* glBlitFramebuffer (see logs) not referenced in any of my GLES headers, but in gl32funcs.h
* From this commit gl32funcs.h is no longer included for GLES2:
https://github.com/reicast/reicast-emulator/blob/a6b773a23e4167f953108e90711d5eeceed37f11/core/rend/g …

Build fails on GLES2 platform after commit a6b773a "Merge pull request #1603"

---

core/hw/mem/_vmem.cpp
core/hw/mem/_vmem.h
core/hw/sh4/dyna/blockmanager-extras.cpp
core/hw/sh4/dyna/blockmanager.cpp
core/hw/sh4/dyna/blockmanager.h
core/hw/sh4/dyna/driver.cpp
core/hw/sh4/dyna/ngen.h
core/linux/common.cpp
core/linux/nixprof/nixprof.cpp
core/rend/TexCache.h
core/windows/winmain.cpp

- Will unlink blocks instead of full cache flush
- Depends on `RBI:AddRef` and `RBI:RemRef` being called correctly
- Prevents stuttering on SMC
- Prerequisite for other aggressive optimizations
- Also moved some unused/debug code to `blockmanager-extras.cpp`
- Will go over it when I revisit the tooling

JIT: Add selective block discards
