reicast/reicast-emulator

- shell/android/src/com/reicast/emulator/FileBrowser.java
- shell/android/src/com/reicast/emulator/config/Config.java
- shell/android/src/com/reicast/emulator/config/InputModFragment.java
- shell/android/src/com/reicast/emulator/periph/MOGAInput.java
- shell/android/src/com/reicast/emulator/periph/MogaHack.java
@skmp It's GNU and not intended to be a long-term solution, but I'm not sure about using this.
> Borrow Moga Lollipop workaround, Add theme backend

- shell/android/res/values-pt/strings.xml
Revised translation and add options that were missing,
> update brazilian translation

- shell/android/AndroidManifest.xml
Travis builds with sdk-21 now, so all is fine
> Enable Android TV options

- shell/android/res/values/strings.xml
- shell/android/src/com/reicast/emulator/emu/GL2JNIView.java
This reverts commit 21fbad3ba50a8adc1630a70199fbf9c046b6351c.
> Revert "Verify freezing is not a context / thread issue"

- core/hw/arm7/arm7.cpp
- core/types.h
- shell/android/res/drawable/rounded.xml
- shell/android/res/layout/menu_popup_debug.xml
- shell/android/res/values/strings.xml
- shell/android/src/com/reicast/emulator/MainActivity.java
- shell/android/src/com/reicast/emulator/emu/OnScreenMenu.java
I don't know why this wasn't already part of this, but it's a first step in automation.
I can post the source for the current log backend if the easiest way is to do the same thing, just on the official server.
> Fix build on OSX, Debug updates, Controller support

- core/build.h
- core/core.mk
- core/hw/aica/dsp.cpp
- core/hw/arm7/arm7.cpp
- core/hw/arm7/virt_arm.cpp
- core/hw/mem/_vmem.cpp
- core/hw/sh4/dyna/blockmanager.cpp
- core/hw/sh4/dyna/decoder.cpp
- core/hw/sh4/dyna/decoder_opcodes.h
- core/hw/sh4/dyna/driver.cpp
- core/hw/sh4/dyna/shil.cpp
- core/hw/sh4/interpr/sh4_interpreter.cpp
- core/linux-dist/main.cpp
- core/linux/common.cpp
- core/linux/nixprof.cpp
- core/nullDC.cpp
- core/profiler/profiler.cpp
- core/rec-ARM/ngen_arm.S
- core/rec-ARM/rec_arm.cpp
- core/rec-x64/rec_x64.cpp
- core/rec-x86/rec_x86_asm.cpp
- core/rec-x86/rec_x86_driver.cpp
- core/rec-x86/rec_x86_il.cpp
- core/windows/winmain.cpp
- shell/android/jni/Android.mk
- shell/android/jni/src/Android.cpp
- shell/gcwz/Makefile
- shell/mac86/Makefile
- shell/nacl/Makefile
- shell/reicast.vcxproj
I've been hacking away on the rec-cpp branch, and I had to do some cleanups on the build defines to get everything working sanely. While I was at it I wrote down some ideas for it. What'ya think?
Figured I'd do this on a separate PR to get feedback (and spell checking...)
> Build defines cleanup

- core/hw/gdrom/gdromv3.cpp
- core/linux/common.cpp
This fixes some gcc warnings (though not all). See individual commit messages for details.
> Fix gcc warnings

- core/linux-dist/main.cpp
> linux-dist/main.cpp cleanups

- core/linux-dist/main.cpp
This are just some aesthetic changes (formatting, whitespace, etc.).
Replaces the cleanup part of #745.
> Fix linux-dist/main.cpp formatting

- core/hw/holly/sb_mem.cpp
- core/hw/sh4/dyna/decoder.cpp
- core/hw/sh4/dyna/shil.cpp
- core/rec-x64/rec_x64.cpp
I cherry-picked some commit from PR #724 (the ones that are not format-string related and can be safely merged).
> Fix some compiler warnings

- core/linux-dist/x11.cpp
- core/rend/gles/gles.cpp
This one enables toggling fullscreen with the F11 key and also fixes window resizing. Resolves #761.
For avoiding merge conflicts, we need to merge #752 & #764 first.
> Linux: Enable x11 fullscreen toggling and fix window resizes

- core/linux-dist/evdev.h
- core/linux-dist/main.cpp
> linux-dist/evdev: Fix evdev_config_key buffer overflow

- core/linux-dist/evdev.h
- core/linux-dist/evdev_mappings.cpp
- core/linux-dist/evdev_mappings.h
> linux-dist/evdev: Use raw button codes

- core/hw/pvr/ta_ctx.cpp
- core/nullDC.cpp
- core/types.h
- shell/android/jni/src/Android.cpp
- shell/android/res/layout/configure_fragment.xml
- shell/android/res/values/strings.xml
- shell/android/src/com/reicast/emulator/config/Config.java
- shell/android/src/com/reicast/emulator/config/OptionsFragment.java
- shell/android/src/com/reicast/emulator/emu/JNIdc.java
- shell/android/src/com/reicast/emulator/emu/OnScreenMenu.java
This replaces #648 in a nicer way. Needs to be tested with problematic hardware.
> sync: Also sync to video if too fast

- shell/linux/Makefile
- shell/linux/man/reicast.1
> Linux: Add install target to Makefile

- appveyor.yml
We might want to budle the exe with some "Ask Toolbar" installer, since
Windows users might be confused if it's not.
> AppVeyor: Add build artifacts

- core/linux-dist/main.cpp
Do we need the curses code? I can't see it serve any particular purpose right now. Might be a leftover from ages ago.
> linux-dist: Remove unneeded code

- core/linux-dist/x11.cpp
> linux/x11: Map X11 ESC key to exit emulator

- shell/linux/Makefile
@skmp This should resolve #795 for the moment.
> Linux/Makefile: Add preliminary NAOMI support

- README.md
The PPA is updated daily, automatically:
https://code.launchpad.net/~random-stuff/+recipe/reicast-daily
There's ARM package too, worked at least on odroid U3.
> Added Ubuntu PPA for development version.

- shell/linux/man/reicast.1
Resolves https://github.com/reicast/reicast-emulator/issues/427#issuecomment-138111981.
> Linux/man: Use gdi as example image file

- core/build.h
- core/hw/sh4/interpr/sh4_fpu.cpp
- core/hw/sh4/interpr/sh4_interpreter.cpp
- core/hw/sh4/interpr/sh4_opcodes.cpp
- core/hw/sh4/modules/mmu.cpp
- core/hw/sh4/modules/mmu.h
- core/hw/sh4/sh4_core.h
- core/hw/sh4/sh4_interrupts.cpp
- core/hw/sh4/sh4_interrupts.h
- core/hw/sh4/sh4_mmr.cpp
- Rewrite mem ops to only modify regs after exception path
- Throw & catch logic for interpreter that raises the exception
- Re-enabled some commented mmu code
DC Linux does work though. No FB emulation but we get to the console prompt :3
> sh4/mmu: C++ exception based sh4 exception support. Won't run wince yet.

- README.md
> README: update Linux build dependencies

- shell/linux/tools/reicast-joyconfig.py
> reicast-joyconfig: Fix crash if button/axis is unnamed

- shell/android/res/values-ru/strings.xml
(values-ru) added missing strings, reworked translation
> [Android] Update values-ru/strings.xml

- core/rend/TexCache.cpp
Street Fighter III 3rd Strike/Capcom Vs SNk 2, possibly others
> Delete spurious code - fixes sprite palette issue with games like

- core/hw/maple/maple_cfg.cpp
In emu.cfg, you can add : 
[players]
nb = 2 // 1 to 4 players
Reicast will add Sega Controller for each players. 
Note : you have to connect and configure each controller if you want play in multiplayer
> Multiplayers with configuration file

- shell/linux/tools/reicast-joyconfig.py
> linux/reicast-joyconfig: Fix keyboard support

- core/hw/maple/maple_cfg.cpp
- core/hw/maple/maple_cfg.h
- core/hw/maple/maple_devs.cpp
- core/hw/maple/maple_devs.h
- core/linux-dist/main.cpp
- core/nacl/nacl.cpp
- core/windows/winmain.cpp
- shell/android/jni/src/Android.cpp
- shell/apple/emulator-ios/emulator/ios_main.mm
- shell/apple/emulator-osx/emulator-osx/osx-main.mm
Some basic controller input for Windows, but rumble required a PuruPuru Pack so added that too.
Quite basic, no error check neither fancy continuous rumble mode but it works. Rez feels nice~
> X360 controller support for Windows + Rumble

- core/hw/maple/maple_cfg.cpp
- core/hw/maple/maple_cfg.h
- core/hw/maple/maple_devs.cpp
- core/hw/maple/maple_devs.h
- core/linux-dist/evdev.cpp
- core/linux-dist/evdev.h
- core/linux-dist/main.cpp
- core/nacl/nacl.cpp
- core/windows/winmain.cpp
- shell/android/jni/src/Android.cpp
- shell/apple/emulator-ios/emulator/ios_main.mm
- shell/apple/emulator-osx/emulator-osx/osx-main.mm
This is a follow-up PR to #877.
> Linux rumble support

- core/hw/pvr/ta.cpp
- Use 256-bit copies
- read pcw from memory
> Cleanup/optimize ta_thd_data32_i

- README.md
> Readme: Add slack link

- core/cfg/cfg.cpp
- core/cfg/cfg.h
- core/hw/pvr/ta_ctx.h
- core/linux-dist/dispmanx.cpp
- core/linux-dist/dispmanx.h
- core/linux-dist/main.cpp
- core/linux/common.cpp
- core/nullDC.cpp
- core/oslib/audiobackend_omx.cpp
- core/oslib/audiobackend_omx.h
- core/oslib/audiostream.cpp
- core/types.h
- shell/linux/Makefile
-Add rpi stuff from OrN: https://github.com/reicast/reicast-emulator/pull/966
-Fix GCC6 issues with "Bool" value name
-Add target RPI3 
-Add platform option mesa so mesa libs or vendor libs can be selected
> rpi stuff from OrN: omx audio backend, and dispmanx window

- .lgtm.yml
I noticed @LoungeKatt's comment in https://github.com/reicast/reicast-emulator/pull/1114#issuecomment-381973339. Here's a small configuration file that will tell lgtm.com how to analyse the C code in reicast-emulator. The first results (if there are any alerts!) will be available on lgtm.com soon; this file is just so you can change LGTM's behaviour in case you change the build process. LGTM will automatically pick up any changes to this file during the analysis. I hope you'll find it useful! Full disclosure: I'm part of the team behind lgtm.com.
If you'd like automatic code review by LGTM, repository admins can enable it here: https://lgtm.com/projects/g/reicast/reicast-emulator/ci. Here's an example from the AMPHTML project of how that works: …
> Add .lgtm.yml file to set up lgtm.com C analysis for reicast-emulator

- core/linux-dist/main.cpp
> Removed unused code in core/linux-dist/main.cpp

- issue_template.md
Differentiate what is required versus optional info.
Document possibility of closing issue when blank.
> Update issue submission form disclaimers

- shell/apple/emulator-ios/emulator/EmulatorView.mm
- shell/apple/emulator-ios/emulator/EmulatorViewController.mm
Adds touchscreen triggers functionality on device and updated EmulatorViewController.mm with MFI Triggers added.
> TouchScreen Triggers added and MFI Controller Update (Stuff)

- core/hw/pvr/Renderer_if.cpp
- core/linux-dist/evdev.cpp
- core/linux-dist/main.cpp
- core/linux-dist/x11.cpp
- core/linux-dist/x11.h
- core/nullDC.cpp
- core/rec-ARM/ngen_arm.S
- core/rec-cpp/rec_cpp.cpp
- core/rec-x64/rec_x64.cpp
- core/rec-x86/rec_lin86_asm.S
- core/rec-x86/rec_x86_asm.cpp
- core/sdl/sdl.cpp
- core/windows/winmain.cpp
- shell/apple/emulator-osx/emulator-osx/AppDelegate.swift
- shell/apple/emulator-osx/emulator-osx/EmuGLView.swift
- shell/apple/emulator-osx/emulator-osx/emulator-osx-Bridging-Header.h
- shell/apple/emulator-osx/emulator-osx/osx-main.mm
Lighter and cleaner version of the previous PR
> Exit cleanly in desktop platforms

- shell/android-studio/reicast/src/main/java/com/reicast/emulator/Emulator.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/MainActivity.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/OptionsFragment.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/JNIdc.java
- shell/android-studio/reicast/src/main/res/layout-v14/configure_fragment.xml
- shell/android-studio/reicast/src/main/res/layout/configure_fragment.xml
- shell/android-studio/reicast/src/main/res/values/strings.xml
This will remove all emulator settings, but will retain the folder configuration (BIOS / games) and any controller or OSD settings beyond the button theme.
> Android: Add a function to remove all settings

- core/linux-dist/main.cpp
Includes the changes from #1239 but without the changes to ``EvdevControllerMapping`` to help test if this also works for more people than myself.
Fixes #1042 and #1035
> evdev: Allow two controls with the same event

- core/rec-cpp/rec_cpp.cpp
Should take care of #1245.
Tested with MvsC 2
> Block checks for rec-cpp

- shell/linux/Makefile
> Linux/Makefile: Disable legacy joystick support

- core/hw/maple/maple_cfg.cpp
- core/hw/maple/maple_cfg.h
- core/hw/maple/maple_devs.h
- core/linux-dist/evdev.cpp
- core/linux-dist/evdev.h
- core/linux-dist/main.cpp
- core/nacl/nacl.cpp
- core/nullDC.cpp
- core/oslib/oslib.h
- core/windows/winmain.cpp
- shell/android-studio/reicast/src/main/jni/src/Android.cpp
- shell/apple/emulator-ios/emulator/ios_main.mm
- shell/apple/emulator-osx/emulator-osx/osx-main.mm
Fixing merge conflicts created for https://github.com/reicast/reicast-emulator/pull/1288
> Allow configuration of maple devices #1288

- .gitignore
- shell/reicast.sln
- shell/reicast.vcxproj
See https://github.com/reicast/reicast-emulator/commit/3579c9aabf673c241253ce184f394a5ec293d848
> vs: Upgrade vcxproj to visual studio 2015

- core/hw/maple/maple_devs.cpp
The VMU which was written to disk was never initialized and therefore consisted only of zeroes.
After saving for the first time the VMU was corrupted.
Changes:
* Not only initialize the VMU in memory but also write the correct contents to disk
* If an existing VMU consists only of zeroes overwrite it with the initial empty VMU
Fixes #758
Might also be related to https://github.com/reicast/gamedb/issues/30
> Maple: Corrected creation of empty VMU

- shell/android-studio/reicast/src/main/java/com/reicast/emulator/MainActivity.java
It's always something, Isn't it? If there is one possible broken way to do something...
> Android: 99 problems and a BIOS ain't one.

- shell/android-studio/reicast/src/main/java/com/reicast/emulator/FileBrowser.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/InputFragment.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/InputModFragment.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/OptionsFragment.java
- shell/android-studio/reicast/src/main/res/values-da/strings.xml
- shell/android-studio/reicast/src/main/res/values-de/strings.xml
- shell/android-studio/reicast/src/main/res/values-es/strings.xml
- shell/android-studio/reicast/src/main/res/values-fr/strings.xml
- shell/android-studio/reicast/src/main/res/values-jp/strings.xml
- shell/android-studio/reicast/src/main/res/values-pt/strings.xml
- shell/android-studio/reicast/src/main/res/values-ru/strings.xml
- shell/android-studio/reicast/src/main/res/values-zh-rCN/strings.xml
- shell/android-studio/reicast/src/main/res/values-zh/strings.xml
- shell/android-studio/reicast/src/main/res/values/strings.xml
Squashing all of the (non-required) warnings based on the new API 26 standard for Google Play
> Android: Complete conversion to API 26 standards

- appveyor.yml
- core/cfg/cfg.h
- core/cfg/cl.cpp
- core/linux-dist/main.cpp
- core/types.h
- core/windows/winmain.cpp
- shell/linux/Makefile
- shell/reicast.sln
- shell/reicast.vcxproj
- shell/reicast.vcxproj.filters
Continuation of https://github.com/reicast/reicast-emulator/pull/1307
> Desktop arg fixes / Auto versioning for VS

- core/hw/aica/aica_if.cpp
- core/hw/gdrom/gdromv3.cpp
- core/hw/holly/holly_intc.cpp
- core/hw/holly/holly_intc.h
- core/hw/maple/maple_if.cpp
- core/hw/pvr/pvr_mem.cpp
- core/hw/pvr/pvr_sb_regs.cpp
- core/hw/sh4/interpr/sh4_interpreter.cpp
- core/hw/sh4/modules/dmac.cpp
- core/nullDC.cpp
- core/types.h
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/Emulator.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/config/PGConfigFragment.java
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/JNIdc.java
- shell/android-studio/reicast/src/main/jni/src/Android.cpp
- shell/android-studio/reicast/src/main/res/layout-v14/pgconfig_fragment.xml
- shell/android-studio/reicast/src/main/res/layout/pgconfig_fragment.xml
- shell/android-studio/reicast/src/main/res/values/strings.xml
This reverts commits e5c0f0e, eebf3fc, 14fc7d9
> [OnHold] Revert "Interrupt Hack setting w/ less stigma"

- shell/android-studio/reicast/src/main/java/com/reicast/emulator/FileBrowser.java
> Only default to a storage list when not searching

- core/nullDC.cpp
Do not save per-game settings if the game name or id is unknown (NAOMI).
> Add cable/region/broadcast to per-game configuration.

- core/README.md
- core/emitter/README.md
- core/hw/gdrom/README.md
- docs/CONTRIBUTING.md
- docs/DreamCast_Specs.md
- docs/Naomi_Overview.md
- docs/neil_corlett_aica_notes.txt
- This is the first step into establishing sustainable and responsible documentation
- Updated core/README to reflect what goes on in the main directory of the codebase
- Added READMEs for GD-ROM and the emitter
- Revised the 1st draft of our CONTRIBUTING doc from old notes released by skmp to our forum
- Added Naomi and Dreamcast specifications
- Found and included some notes on AICA (not mine, if possible find the guy that wrote them and accredit him) 
- Initialize Doxygen support after the port of building to CMake
- Add:
* Getting_Started.md
* Guidelines to existing and new contributors
* Git workflow specification
* Code of Conduct
* Recommended Reading 
* HISTORY.md
* Testing guidelines per platfrom
> Documentation additions

- core/rend/gles/gles.cpp
- core/rend/gles/gles.h
Fix for https://github.com/reicast/reicast-emulator/issues/549
> Texture-based fog table

- core/rend/gles/gles.cpp
- core/rend/gles/gles.h
Fix issues with pixel scaling and scissoring.
Wacky Races should now be playable.
> Enable log2 depth at runtime when supported (GL, GLES 3)

- core/deps/chdpsr/cdipsr.cpp
- core/deps/chdpsr/cdipsr.h
- core/imgread/cdi.cpp
Less console spam, better error reporting
Adopt https://github.com/reicast/reicast-emulator/commit/bed7a83b772db44f1ccbcfc176a02adf410bbddf from @flyinghead to main.
> Check CDI version to avoid loading any crap as a CDI image and crashing

- shell/android-studio/reicast/src/main/java/com/reicast/emulator/emu/VirtualJoystickDelegate.java
avoid lag when spamming the touchscreen controls
> android: run the vibrator in a separate thread

- core/hw/maple/maple_cfg.cpp
- core/hw/maple/maple_cfg.h
- core/hw/maple/maple_devs.cpp
- core/hw/naomi/naomi.cpp
- core/hw/naomi/naomi_cart.cpp
- core/hw/naomi/naomi_cart.h
- core/linux-dist/x11.cpp
- core/nullDC.cpp
- core/rend/gl4/gldraw.cpp
- core/rend/gl4/gles.cpp
- core/rend/gles/CustomTexture.cpp
- core/rend/gles/CustomTexture.h
- core/rend/gles/gldraw.cpp
- core/rend/gles/gles.cpp
- core/rend/gles/gles.h
- core/rend/gles/gltex.cpp
- core/rend/gles/imgui_impl_opengl3.cpp
- core/rend/gui.cpp
- core/types.h
- core/windows/winmain.cpp
- shell/android-studio/reicast/src/main/java/com/reicast/emulator/BaseGLActivity.java
- Improve Naomi/AW input system (use game input descriptors)
- Fix race conditions when loading custom textures
- Clear color buffer before drawing imgui background
- Add horizontal screen stretching option
> Improve Naomi/AW input system. Fix custom texture loading race conditions

- core/nullDC.cpp
- core/oslib/audiobackend_alsa.cpp
- core/oslib/audiobackend_alsa.h
- core/oslib/audiobackend_android.h
- core/oslib/audiobackend_coreaudio.cpp
- core/oslib/audiobackend_coreaudio.h
- core/oslib/audiobackend_directsound.cpp
- core/oslib/audiobackend_directsound.h
- core/oslib/audiobackend_libao.cpp
- core/oslib/audiobackend_libao.h
- core/oslib/audiobackend_omx.cpp
- core/oslib/audiobackend_omx.h
- core/oslib/audiobackend_oss.cpp
- core/oslib/audiobackend_oss.h
- core/oslib/audiobackend_pulseaudio.cpp
- core/oslib/audiobackend_pulseaudio.h
- core/oslib/audiostream.cpp
- core/oslib/audiostream.h
- core/rend/gui.cpp
- core/types.h
- shell/android-studio/reicast/src/main/jni/src/Android.cpp
This allows for the audio backend to be configurable via the GUI.
> AUDIO: Make backend configurable

- core/oslib/audiobackend_alsa.cpp
- core/oslib/audiobackend_coreaudio.cpp
- core/oslib/audiobackend_directsound.cpp
- core/oslib/audiobackend_libao.cpp
- core/oslib/audiobackend_omx.cpp
- core/oslib/audiobackend_oss.cpp
- core/oslib/audiobackend_pulseaudio.cpp
- core/oslib/audiobackend_sdl2.cpp
- core/oslib/audiobackend_xaudio.cpp
- core/oslib/audiostream.cpp
- core/oslib/audiostream.h
- core/windows/winmain.cpp
- shell/android-studio/reicast/src/main/jni/src/Android.cpp
- shell/linux/Makefile
- shell/reicast.vcxproj
- shell/reicast.vcxproj.filters
Only dsound and sdl2 implemented as pull style, and the dsound implementation is rather messy.
> Added support for pull-style audiostream, including resampling pulls.

- core/linux/posix_vmem.cpp
- core/stdclass.h
- core/windows/win_vmem.cpp
- shell/linux/Makefile
- wercker.yml
Let's hope it does not break again.
> Fix no exceptions and add tests for it and no-rwx too

- shell/linux/Makefile
add platform sun8i
for legacy (non mainline) use sdl
> add platform sun8i

- core/oslib/audiostream.cpp
fix make problems with orange pi/banana pi/tritium h3
look@
https://github.com/reicast/reicast-emulator/pull/1597
> fix make problem with pi
